version: "3.8"

services:
  api-local:
    build: .
    environment:
      PORT: 80
      SENTRY_DSN: ""
      MONGO_CLUSTER_URL: mongodb://root:example@mongo:27017
      MONGO_DATABASE: local
    ports:
      - 8081:80
    command: mvn exec:java -D persistence=mongo

  api-remote:
    image: ghcr.io/glo-2003-h25-eq12/glo-2003-splitul:remise4
    environment:
      PORT: 80
      SENTRY_DSN: ""
      MONGO_CLUSTER_URL: mongodb://root:example@mongo:27017
      MONGO_DATABASE: local
    ports:
      - 8082:80
    command: mvn exec:java -D persistence=mongo

  mongo:
    image: mongo:8
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8083:8083
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongo: